// *************************************
// Modula Replication Engine
// Utilities
// 'replication_task.hh'
// Author: jcjuarez
// *************************************

#ifndef REPLICATION_TASK_
#define REPLICATION_TASK_

#include "utilities.hh"

#include <string>

namespace modula
{

//
// Replication action enum class.
//
enum class replication_action : uint8
{

    //
    // File needs to be created.
    //
    create = 0,

    //
    // File needs to be modified.
    //
    update = 1,

    //
    // File needs to be removed.
    //
    remove = 2,

    //
    // Full sync needs to be performed over the specified replication engines.
    //
    full_sync = 3,

    //
    // Invalid replication action.
    //
    invalid = 4
    
};

//
// Replication task class for filesystem events generated by the filesystem monitor.
//
class replication_task
{

public:

    //
    // Constructor. Initializes a replication task.
    //
    replication_task(
        replication_action p_replication_action,
        const std::string& p_file_name);

    replication_action
    get_replication_action() const;

    std::string
    get_file_name() const;

private:

    //
    // Replication action of the task.
    //
    replication_action m_replication_action;

    //
    // Name of the file tied to the task.
    //
    std::string m_file_name;
    
};

} // namespace modula.

#endif
